"""empty message

Revision ID: 01e2ee8242bf
Revises: e4180e812773
Create Date: 2017-07-06 20:24:02.852667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e2ee8242bf'
down_revision = 'e4180e812773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_hash')
    # ### end Alembic commands ###
